version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - NGROK_TOKEN=${NGROK_TOKEN}
      - REPO_URL=${REPO_URL}
    volumes:
      - .:/app
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
